# docker-compose.yml

services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/faiss_index_langchain:/app/faiss_index_langchain # Mount FAISS index
    env_file:
      - ./backend/.env

  frontend:
    build: .
    container_name: rag-frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
